// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

class Element {
  btn1 = 'btn_1';
  btn2 = 'btn_2';
  btn3 = 'btn_3';
  btn4 = 'btn_4';
  btn5 = 'btn_5';
  btn6 = 'btn_6';
  btn7 = 'btn_7';
  btn8 = 'btn_8';
  btn9 = 'btn_9';
  btn0 = 'btn_0';
  btnPlus = 'btn_plus';
  btnMinus = 'btn_minus';
  btnMultiply = 'btn_multiply';
  btnDivide = 'btn_divide';
  btnEqual = 'btn_equal';
  display = 'display';
  constructor(){}
}

describe('calculator', function() {
  this.timeout(30000)
  let driver
  let vars
  const element = new Element();
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('calculator', async function() {
    await driver.get("http://localhost:4200/calculator")
    await driver.manage().window().setRect({ width: 1878, height: 936 })
    await driver.findElement(By.id(element.btn1)).click()
    await driver.findElement(By.id(element.btn2)).click()
    await driver.findElement(By.id(element.btnPlus)).click()
    await driver.findElement(By.id(element.btn4)).click()
    await driver.findElement(By.id(element.btn5)).click()
    await driver.findElement(By.id(element.btnEqual)).click()
    assert.equal(await driver.findElement(By.id(element.display)).getText(), '12+45=57')
  })

  it('0.1*3', async function() {
    await driver.get("http://localhost:4200/calculator")
    await driver.findElement(By.id(element.btn1)).click()
    await driver.findElement(By.id(element.btnDivide)).click()
    await driver.findElement(By.id(element.btn1)).click()
    await driver.findElement(By.id(element.btn0)).click()
    await driver.findElement(By.id(element.btnEqual)).click()
    await driver.findElement(By.id(element.btnMultiply)).click()
    await driver.findElement(By.id(element.btn3)).click()
    await driver.findElement(By.id(element.btnEqual)).click()
    let result = await driver.findElement(By.id(element.display)).getText()
    result = result.substring(result.indexOf('=') + 1, result.length)
    result = Number(result)
    assert.equal(result, 0.3)
  })
})
