// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

class Element {
  inputHeroName = 'input_hero_name';
  inputHeroDescription = 'input_hero_description';
  buttonAddHero = 'btn_add_hero';
  labelHeroName = 'label_hero_name_';
  labelHeroDescription = 'label_hero_description_';

  constructor(){}

  getLabelHeroName(index){
    return `label_hero_name_${index}`;
  }

  getLabelHeroDescription(index){
    return `label_hero_description_${index}`;
  }

}

describe('heroes', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('happy path', async function() {
    await driver.get("http://localhost:4200/heroes")
    await driver.manage().window().setRect({ width: 1878, height: 936 })
    await driver.findElement(By.id("input_hero_name")).click()
    await driver.findElement(By.id("input_hero_name")).sendKeys("Thor")
    await driver.findElement(By.id("input_hero_description")).click()
    await driver.findElement(By.id("input_hero_description")).sendKeys("God of Thunder")
    await driver.findElement(By.id("btn_add_hero")).click()
    assert.equal(await driver.findElement(By.id("label_hero_name_2")).getText(), "Thor")
    assert.equal(await driver.findElement(By.id("label_hero_description_2")).getText(), "God of Thunder")
  })

  it('add hero empty name hero', async function() {
    await driver.get("http://localhost:4200/heroes")
    await driver.manage().window().setRect({ width: 1878, height: 936 })
    await driver.findElement(By.id("input_hero_name")).click()
    await driver.findElement(By.id("input_hero_name")).sendKeys("")
    await driver.findElement(By.id("input_hero_description")).click()
    await driver.findElement(By.id("input_hero_description")).sendKeys("God of Thunder")
    // check that button is disabled
    assert.equal(await driver.findElement(By.id("btn_add_hero")).getAttribute("disabled"), "true")
  })

  it('remove hero from list', async function() {
    await driver.get("http://localhost:4200/heroes")
    await driver.manage().window().setRect({ width: 1878, height: 936 })
    await driver.findElement(By.id("input_hero_name")).click()
    await driver.findElement(By.id("input_hero_name")).sendKeys("Thor")
    await driver.findElement(By.id("input_hero_description")).click()
    await driver.findElement(By.id("input_hero_description")).sendKeys("God of Thunder")
    await driver.findElement(By.id("btn_add_hero")).click()
    await driver.findElement(By.id("btn_remove_hero_2")).click()
    // check that element label_hero_name_2 does not exist
    try {
      assert.equal(await driver.findElement(By.id("label_hero_name_2")).getText(), "")
      assert.equal(true, false)
    } catch (err) {
      assert.equal(err.name, "NoSuchElementError")
    }
  }
  )

})
