// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test 1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test 1', async function() {
    await driver.get("http://localhost:4200/calculator")
    await driver.findElement(By.css(".calculator__key:nth-child(8)")).click()
    await driver.findElement(By.css(".calculator__key:nth-child(9)")).click()
    await driver.findElement(By.css(".calculator__key:nth-child(3)")).click()
    await driver.findElement(By.css(".calculator__key:nth-child(13)")).click()
    await driver.findElement(By.css(".calculator__key:nth-child(12)")).click()
    await driver.findElement(By.css(".calculator__key--enter")).click()
    await driver.findElement(By.css(".calculator__key:nth-child(1)"))
  })
})
